### ISSUE TITLE
Any plans to support CardDav?

### ISSUE THREAD

**Issue by donatj** [taviti/caldav-go#10]

**Comment by matthew-davie** [comment]
No plans to add additional support to this project, although we will merge improvements and bug fixes that the community posts to the project. So if you add it, just post back here in a pull request and we'll take a look and merge!

**Comment by donatj** [comment]
Good deal. Thanks for the response. This may be a jumping off point for a work side project.

**Comment by matthew-davie** [comment]
Excellent - we'd love to see it continue to mature, we just don't have the
resources to put on it presently...
